### ISSUE TITLE
[Unholy Entity] Skill 4 teleport error

### ISSUE THREAD

**Issue by NosferatuJoe** [ManifestManah/Racepack-Holliday-V2#1]
I found this in my logs:

```
2021-02-16 12:04:54 - sp	-	MESSAGE	[Race] : Unholy Entity - [Block] Skill : 4 ( START )
2021-02-16 12:04:54 - sp	-	MESSAGE	[Race] : Unholy Entity - [Block] Skill : 4 ( CHECKS START )
2021-02-16 12:04:54 - sp	-	MESSAGE	[Race] : Unholy Entity - [Block] Skill : 4 ( EXECUTED START )
2021-02-16 12:04:54 - sp	-	MESSAGE	[Race] : Unholy Entity - [Block] Skill : 4 ( EXECUTED END )
2021-02-16 12:04:54 - sp	-	MESSAGE	[Race] : Unholy Entity - [Block] Skill : 4 ( CHECKS END )
2021-02-16 12:04:54 - sp	-	MESSAGE	[Race] : Unholy Entity - [Block] Skill : 4 ( END )
2021-02-16 12:04:55 - sp	-	MESSAGE	Sub command "#a" not found.
2021-02-16 12:04:55 - sp	-	MESSAGE	Sub command "#a" not found.
2021-02-16 12:04:56 - sp	-	MESSAGE	Not enough arguments:
  wcs_teleport <player:userid> <x:float> <y:float> <z:float>
2021-02-16 12:04:56 - sp	-	EXCEPTION	
[SP] Caught an Exception:
Traceback (most recent call last):
  File "../addons/source-python/plugins/commandsx/commandsx.py", line 121, in _wcs_teleport
    userid = int(command[1])

ValueError: invalid literal for int() with base 10: '73.4825210571289'


2021-02-16 12:04:57 - sp	-	MESSAGE	Not enough arguments:
  wcs_teleport <player:userid> <x:float> <y:float> <z:float>
2021-02-16 12:04:57 - sp	-	EXCEPTION	
[SP] Caught an Exception:
Traceback (most recent call last):
  File "../addons/source-python/plugins/commandsx/commandsx.py", line 121, in _wcs_teleport
    userid = int(command[1])

ValueError: invalid literal for int() with base 10: '-777.8131103515625'
```

Guess there is an issue with the wcs_teleport values.

**Comment by ManifestManah** [comment]
I have been unable to replicate the error you've posted, but I noticed a mistake in terms of the delays and fixed that.
This will be available in the next major update.
